# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CounterName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('count', models.IntegerField(max_length=99999)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='CounterName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.CounterName'),
        ),
    ]
