# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countername',
            name='count',
            field=models.IntegerField(),
        ),
    ]
