# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 04:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20180101_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCount', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 1, 2, 9, 42, 38, 286719))),
            ],
        ),
        migrations.RemoveField(
            model_name='chart',
            name='CounterName',
        ),
        migrations.RemoveField(
            model_name='countername',
            name='count',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.AddField(
            model_name='netcount',
            name='CounterName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.CounterName'),
        ),
    ]
