# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20180102_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netcount',
            name='numCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='netcount',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 18, 39, 54, 316147)),
        ),
    ]
