# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20180102_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='countername',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='netcount',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 18, 57, 39, 342989)),
        ),
    ]
